export const TOGGLE_SIDEBAR = 'TOGGLE_SIDEBAR'

export const LOGIN_REQUEST = 'LOGIN_REQUEST'
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS'
export const LOGIN_FAILURE = 'LOGIN_FAILURE'
export const LOGOUT_SUCCESS = 'LOGOUT_SUCCESS'

export const FETCH_EVENTS_START = 'FETCH_EVENTS_START'
export const FETCH_EVENTS_SUCCESS = 'FETCH_EVENTS_SUCCESS'
export const FETCH_EVENTS_FAIL = 'FETCH_EVENTS_FAIL'

export const UPDATE_CURRENT_EVENT = 'UPDATE_CURRENT_EVENT'

export const UPDATE_ALL_EVENTS = 'UPDATE_ALL_EVENTS'

export const FETCH_DASHBOARD_START = 'FETCH_DASHBOARD_START'
export const FETCH_DASHBOARD_GUEST_SUCCESS = 'FETCH_DASHBOARD_GUEST_SUCCESS'
export const FETCH_DASHBOARD_TODO_SUCCESS = 'FETCH_DASHBOARD_TODO_SUCCESS'
export const FETCH_DASHBOARD_FAIL = 'FETCH_DASHBOARD_FAIL'
export const UPDATE_CURRENT_DASHBOARD = 'UPDATE_CURRENT_DASHBOARD'
